<?php
// filepath: /home/sbandaog/42/webserv/www/cgi/php_demo.php

// CGI Headers are automatically handled by PHP
header('Content-Type: text/html; charset=utf-8');

$currentTime = date('Y-m-d H:i:s');
$phpVersion = phpversion();
$serverInfo = $_SERVER['SERVER_SOFTWARE'] ?? 'Unknown';
$requestMethod = $_SERVER['REQUEST_METHOD'] ?? 'Unknown';
$serverName = $_SERVER['SERVER_NAME'] ?? 'Unknown';
$serverPort = $_SERVER['SERVER_PORT'] ?? 'Unknown';
$queryString = $_SERVER['QUERY_STRING'] ?? 'Empty';
$userAgent = $_SERVER['HTTP_USER_AGENT'] ?? 'Not provided';
$remoteAddr = $_SERVER['REMOTE_ADDR'] ?? 'Unknown';
$scriptName = $_SERVER['SCRIPT_NAME'] ?? 'Unknown';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PHP CGI Demo - Webserv</title>
    <link rel="stylesheet" href="../css/style.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>
        .php-theme {
            background: linear-gradient(135deg, #663399 0%, #8e44ad 100%);
        }
        .php-card {
            background: white;
            border-left: 6px solid #663399;
            border-radius: 12px;
            padding: 25px;
            margin: 20px 0;
            box-shadow: 0 8px 25px rgba(102, 51, 153, 0.15);
        }
        .php-badge {
            background: linear-gradient(45deg, #663399, #8e44ad);
            color: white;
            padding: 8px 16px;
            border-radius: 20px;
            font-weight: bold;
            display: inline-block;
            margin: 10px 0;
        }
        .code-block {
            background: #2d3748;
            color: #e2e8f0;
            padding: 20px;
            border-radius: 8px;
            font-family: monospace;
            margin: 15px 0;
            border-left: 4px solid #663399;
        }
        .env-table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        .env-table th, .env-table td {
            text-align: left;
            padding: 12px;
            border-bottom: 1px solid #ddd;
        }
        .env-table th {
            background: #f8f9fa;
            font-weight: 600;
            color: #333;
        }
        .env-table tr:hover {
            background: #f8f0ff;
        }
        .php-highlight {
            color: #663399;
            font-weight: bold;
        }
    </style>
</head>
<body class="php-theme">
    <div class="background-pattern"></div>
    
    <header>
        <div class="header-content">
            <div class="logo">
                <div class="logo-icon">🌐</div>
                <h1>PHP CGI Script</h1>
            </div>
            <p class="subtitle">Dynamically generated by PHP <?php echo $phpVersion; ?></p>
        </div>
    </header>

    <main class="container">
        <section class="intro">
            <h2>✅ PHP CGI Execution Successful!</h2>
            <p>This page was generated server-side by a PHP CGI script</p>
            <div class="php-badge">🌐 Powered by PHP <?php echo $phpVersion; ?></div>
        </section>

        <div class="php-card">
            <h3 style="color: #663399; margin-bottom: 15px;">🕒 Execution Information</h3>
            <p><strong>Generated at:</strong> <?php echo $currentTime; ?></p>
            <p><strong>PHP Version:</strong> <?php echo $phpVersion; ?></p>
            <p><strong>Server Software:</strong> <?php echo $serverInfo; ?></p>
            <p><strong>Script Path:</strong> <?php echo $scriptName; ?></p>
            <p><strong>Process ID:</strong> <?php echo getmypid(); ?></p>
        </div>

        <div class="php-card">
            <h3 style="color: #663399; margin-bottom: 15px;">🌐 Request Information</h3>
            <table class="env-table">
                <tr>
                    <th>Parameter</th>
                    <th>Value</th>
                </tr>
                <tr>
                    <td>Request Method</td>
                    <td class="php-highlight"><?php echo $requestMethod; ?></td>
                </tr>
                <tr>
                    <td>Server Name</td>
                    <td><?php echo $serverName; ?></td>
                </tr>
                <tr>
                    <td>Server Port</td>
                    <td><?php echo $serverPort; ?></td>
                </tr>
                <tr>
                    <td>Query String</td>
                    <td><?php echo $queryString; ?></td>
                </tr>
                <tr>
                    <td>User Agent</td>
                    <td><?php echo htmlspecialchars($userAgent); ?></td>
                </tr>
                <tr>
                    <td>Remote Address</td>
                    <td><?php echo $remoteAddr; ?></td>
                </tr>
                <tr>
                    <td>Current Time</td>
                    <td class="php-highlight"><?php echo $currentTime; ?></td>
                </tr>
            </table>
        </div>

        <div class="php-card">
            <h3 style="color: #663399; margin-bottom: 15px;">💻 PHP Code Sample</h3>
            <p>Here's the PHP code that generated this page:</p>
            <div class="code-block">
<span style="color: #ff6b6b;">&lt;?php</span><br>
<span style="color: #4ecdc4;">$currentTime</span> = <span style="color: #ffe66d;">date</span>(<span style="color: #95e1d3;">'Y-m-d H:i:s'</span>);<br>
<span style="color: #4ecdc4;">$phpVersion</span> = <span style="color: #ffe66d;">phpversion</span>();<br>
<span style="color: #4ecdc4;">$serverName</span> = <span style="color: #4ecdc4;">$_SERVER</span>[<span style="color: #95e1d3;">'SERVER_NAME'</span>];<br><br>

<span style="color: #ffe66d;">echo</span> <span style="color: #95e1d3;">"Generated at: "</span> . <span style="color: #4ecdc4;">$currentTime</span>;<br>
<span style="color: #ff6b6b;">?&gt;</span>
            </div>
        </div>

        <div class="php-card">
            <h3 style="color: #663399; margin-bottom: 15px;">🔧 PHP Configuration</h3>
            <p><strong>Memory Limit:</strong> <?php echo ini_get('memory_limit'); ?></p>
            <p><strong>Max Execution Time:</strong> <?php echo ini_get('max_execution_time'); ?> seconds</p>
            <p><strong>Upload Max Filesize:</strong> <?php echo ini_get('upload_max_filesize'); ?></p>
            <p><strong>Post Max Size:</strong> <?php echo ini_get('post_max_size'); ?></p>
        </div>

        <section class="back-navigation" style="text-align: center;">
            <a href="/demo/cgi.html" class="back-button" style="background: rgba(255, 255, 255, 0.9);">
                <span class="back-button-icon">⬅️</span>
                <span>Back to CGI Demo</span>
            </a>
        </section>
    </main>

    <footer style="background: rgba(0, 0, 0, 0.2);">
        <div class="footer-content">
            <p>&copy; 2025 Webserv Project. Generated by PHP CGI.</p>
            <div class="footer-links">
                <a href="/">Main Demo</a>
                <a href="/demo/cgi.html">CGI Tests</a>
            </div>
        </div>
    </footer>
</body>
</html>