#!/usr/bin/env python3
# filepath: /home/sbandaog/42/webserv/www/cgi/python_demo.py

import os
import datetime
import platform
import sys

# CGI Header
print("Content-Type: text/html\r")
print("\r")

# HTML Content
html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Python CGI Demo - Webserv</title>
    <link rel="stylesheet" href="/css/style.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>
        .python-theme {{
            background: linear-gradient(135deg, #3776ab 0%, #ffd43b 100%);
        }}
        .python-card {{
            background: white;
            border-left: 6px solid #3776ab;
            border-radius: 12px;
            padding: 25px;
            margin: 20px 0;
            box-shadow: 0 8px 25px rgba(55, 118, 171, 0.15);
        }}
        .python-badge {{
            background: linear-gradient(45deg, #3776ab, #ffd43b);
            color: white;
            padding: 8px 16px;
            border-radius: 20px;
            font-weight: bold;
            display: inline-block;
            margin: 10px 0;
        }}
        .code-block {{
            background: #2d3748;
            color: #e2e8f0;
            padding: 20px;
            border-radius: 8px;
            font-family: monospace;
            margin: 15px 0;
            border-left: 4px solid #3776ab;
        }}
        .env-table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }}
        .env-table th, .env-table td {{
            text-align: left;
            padding: 12px;
            border-bottom: 1px solid #ddd;
        }}
        .env-table th {{
            background: #f8f9fa;
            font-weight: 600;
            color: #333;
        }}
        .env-table tr:hover {{
            background: #f0f4ff;
        }}
    </style>
</head>
<body class="python-theme">
    <div class="background-pattern"></div>
    
    <header>
        <div class="header-content">
            <div class="logo">
                <div class="logo-icon">🐍</div>
                <h1>Python CGI Script</h1>
            </div>
            <p class="subtitle">Dynamically generated by Python {platform.python_version()}</p>
        </div>
    </header>

    <main class="container">
        <section class="intro">
            <h2>✅ Python CGI Execution Successful!</h2>
            <p>This page was generated server-side by a Python CGI script</p>
            <div class="python-badge">🐍 Powered by Python {platform.python_version()}</div>
        </section>

        <div class="python-card">
            <h3 style="color: #3776ab; margin-bottom: 15px;">🕒 Execution Information</h3>
            <p><strong>Generated at:</strong> {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            <p><strong>Python Version:</strong> {platform.python_version()}</p>
            <p><strong>Platform:</strong> {platform.system()} {platform.release()}</p>
            <p><strong>Script Path:</strong> {os.environ.get('SCRIPT_NAME', 'Unknown')}</p>
        </div>

        <div class="python-card">
            <h3 style="color: #3776ab; margin-bottom: 15px;">🌐 Request Information</h3>
            <table class="env-table">
                <tr>
                    <th>Parameter</th>
                    <th>Value</th>
                </tr>
                <tr>
                    <td>Request Method</td>
                    <td>{os.environ.get('REQUEST_METHOD', 'Not set')}</td>
                </tr>
                <tr>
                    <td>Server Name</td>
                    <td>{os.environ.get('SERVER_NAME', 'Not set')}</td>
                </tr>
                <tr>
                    <td>Server Port</td>
                    <td>{os.environ.get('SERVER_PORT', 'Not set')}</td>
                </tr>
                <tr>
                    <td>Query String</td>
                    <td>{os.environ.get('QUERY_STRING', 'Empty')}</td>
                </tr>
                <tr>
                    <td>User Agent</td>
                    <td>{os.environ.get('HTTP_USER_AGENT', 'Not provided')}</td>
                </tr>
                <tr>
                    <td>Remote Address</td>
                    <td>{os.environ.get('REMOTE_ADDR', 'Unknown')}</td>
                </tr>
            </table>
        </div>

        <div class="python-card">
            <h3 style="color: #3776ab; margin-bottom: 15px;">💻 Python Code Sample</h3>
            <p>Here's the Python code that generated this page:</p>
            <div class="code-block">
import os<br>
import datetime<br>
import platform<br><br>

# CGI Header<br>
print("Content-Type: text/html\\r")<br>
print("\\r")<br><br>

# Get current time<br>
now = datetime.datetime.now()<br>
print(f"Generated at: {{now.strftime('%Y-%m-%d %H:%M:%S')}}")
            </div>
        </div>

        <section class="back-navigation" style="text-align: center;">
            <a href="/demo/cgi.html" class="back-button" style="background: rgba(255, 255, 255, 0.9);">
                <span class="back-button-icon">⬅️</span>
                <span>Back to CGI Demo</span>
            </a>
        </section>
    </main>

    <footer style="background: rgba(0, 0, 0, 0.2);">
        <div class="footer-content">
            <p>&copy; 2025 Webserv Project. Generated by Python CGI.</p>
            <div class="footer-links">
                <a href="/">Main Demo</a>
                <a href="/demo/cgi.html">CGI Tests</a>
            </div>
        </div>
    </footer>
</body>
</html>"""

print(html_content)